feat: setup jest config & create some test for reducer & thunk function

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,18 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-pnpm lint --fix
-pnpm format
+echo '🛠️ Styling your project before committing 🛠️'
+echo 'Please wait, this may take a while...'
+
+# check eslint standard
+pnpm lint || (
+  echo '💀 Oops.. you have a problem with your code 💀'
+  echo 'Fix it first, then commit it again'
+  false;
+)
+
+echo '✅ No error found: you can commit your code now 🚀🚀'
+
+
+
+
